### ISSUE TITLE
Configuration doc needed w.r.t. hot reload

### ISSUE THREAD

**Issue by kwesterfeld** [mikz/jspm-dev-server#1]
Is there a doc you can point to that explains the following?

I eagerly installed and tried to use this server, since it really handles my use-case regarding the proxy to back-end sources.  I want to ditch a bunch of stuff I have configured for servings static pages and such for my development workflow.

The problem I see is that I do not know how to setup the socket emitter because this server uses HTTPS, while the socket emitter is on a separate non-HTTPS port, causing mixed protocol errors in chrome.

What's the step-by-step?

Thanks!

**Comment by HeinrichFilter** [comment]
@kwesterfeld I had the same problem.

After looking at the code I saw that the same `server` instance is used to serve the static files, do the proxying and run the `chokidar-socket-emitter`.

See https://github.com/mikz/jspm-dev-server/blob/master/index.js#L77

That means you have to change the capaj/systemjs-hot-reloader script in your project HTML to use the same port as jspm-dev-server (by default port 3000) and change it to use https.

E.g. in my entry point HTML I have the following now:

``` html
  <script type="text/javascript">
    if (location.origin.match(/localhost/)) {
        System.trace = true
        System.import('capaj/systemjs-hot-reloader').then(function(HotReloader){
            new HotReloader.default('https://localhost:3000')  // chokidar-socket-emitter port
        })
    }
  </script>
```

**Comment by kwesterfeld** [comment]
Thank you so much for this!  I will check out your config, adapting it to what I wanted to do, and report my findings

**Comment by kwesterfeld** [comment]
Working AWESOME...thanks.  

My app is much-broken with http/2, unfortunately.  I'm working at it, however.  I can see the potential for parallel load....drops my load of unbundled app with > 200 http requests from 8s+ to @300ms.  WOW.

The instructions should likely look more like this, with removal of protocol, btw:

```
  <script type="text/javascript">
    if (location.origin.match(/localhost/)) {
        System.trace = true
        System.import('capaj/systemjs-hot-reloader').then(function(HotReloader){
            new HotReloader.default('//localhost:3000')  // chokidar-socket-emitter port
        })
    }
  </script>
```
