### ISSUE TITLE
Browser sync?

### ISSUE THREAD

**Issue by amcdnl** [mikz/jspm-dev-server#2]
Why not use browser sync instead of serve-static?

**Comment by mikz** [comment]
browsersync does not support http/2 (https://github.com/BrowserSync/browser-sync/issues/766) which is the sole purpose of this dev server

I like browsersync and could see this as its extension. I even had a jspm hot reloader prototype. But HTTP/2 is the requirement here.

**Comment by amcdnl** [comment]
@mikz awesome, didn't realize that was the primary reason for the proj. Thanks for update

**Comment by amcdnl** [comment]
@mikz actually, u can run http2 w/ BS - https://github.com/BrowserSync/browser-sync/pull/856

**Comment by mikz** [comment]
Interesting. Could not find that before. 

What benefits would browsersync bring? I know the features like syncing across browsers etc. So the benefit would be to use browsersync features with and have a prepared bundle for hot reloading?

**Comment by amcdnl** [comment]
1) CSS Injection
2) Cross-browser sync ( scroll / reload / etc )
3) Built in watcher ( don't really need here tho )
4) Network throttling for testing ( spdy can prob do that tho )

Its already hooking a socket, u can use that to determine when to re-pull and whatnot for hot reload.

**Comment by mikz** [comment]
@amcdnl https://github.com/BrowserSync/browser-sync/pull/856 was closed, not merged, so BrowserSync does not support HTTP/2. And correct issue to track it is https://github.com/BrowserSync/browser-sync/issues/766.

Closing this until BrowserSync gets HTTP/2 support.
